import React, { useState } from 'react'
import { Bell, Shield, Info, AlertCircle, CheckCircle, Trash2, Search, Filter } from 'lucide-react'

const MOCK_NOTIFICATIONS = [
  { id: 1, title: 'New Registration: Maruti Logistics', message: 'A new transport business "Maruti Logistics" has registered from Gurgaon, Haryana.', type: 'info', time: '5 mins ago', read: false },
  { id: 2, title: 'High-Value Bill Generated', message: 'An invoice of ₹54,000 has been generated by "Radhe Tempo Service". Status: Pending.', type: 'alert', time: '1 hour ago', read: false },
  { id: 3, title: 'System Security Update', message: 'The administrative login firewall has been updated successfully to version 4.2.1.', type: 'security', time: '4 hours ago', read: true },
  { id: 4, title: 'New Garage Partner', message: 'City Auto Workshop (Delhi) has completed their onboarding documentation.', type: 'success', time: '1 day ago', read: true },
  { id: 5, title: 'Support Ticket #8841', message: 'A user is reporting issues with PDF generation in Android Chrome. Investigation required.', type: 'alert', time: '2 days ago', read: true }
]

export default function AdminNotifications() {
  const [notifications, setNotifications] = useState(MOCK_NOTIFICATIONS)
  const accentColor = '#7C3AED'

  const markAllRead = () => {
    setNotifications(prev => prev.map(n => ({ ...n, read: true })))
  }

  const deleteOne = (id) => {
    setNotifications(prev => prev.filter(n => n.id !== id))
  }

  const getIcon = (type) => {
    switch (type) {
      case 'alert':    return <AlertCircle size={20} color="#DC2626" />
      case 'security': return <Shield size={20} color="#EF4444" />
      case 'success':  return <CheckCircle size={20} color="#16A34A" />
      case 'info':     return <Info size={20} color="#2563EB" />
      default:         return <Bell size={20} color={accentColor} />
    }
  }

  return (
    <div className="animate-fadeIn">
      <div className="flex items-center justify-between mb-8">
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
            <Bell size={18} color={accentColor} />
            <span style={{ fontSize: '0.7rem', fontWeight: 800, color: accentColor, textTransform: 'uppercase', letterSpacing: '0.08em' }}>
              System Alerts · Notifications
            </span>
          </div>
          <h1 style={{ fontSize: '1.75rem', fontWeight: 900, margin: 0 }}>System Notifications</h1>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', margin: '4px 0 0' }}>
            Monitor real-time system activities and security alerts
          </p>
        </div>
        <button className="btn btn-ghost" onClick={markAllRead} style={{ fontWeight: 700 }}>
          Mark all as read
        </button>
      </div>

      <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
        <div style={{ padding: '16px 24px', borderBottom: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: 'var(--bg-alt)' }}>
          <div style={{ display: 'flex', gap: 20 }}>
             <button className="btn btn-ghost btn-sm" style={{ border: 'none', background: 'transparent', color: accentColor, fontWeight: 800 }}>All</button>
             <button className="btn btn-ghost btn-sm" style={{ border: 'none', background: 'transparent', fontWeight: 700 }}>Unread</button>
             <button className="btn btn-ghost btn-sm" style={{ border: 'none', background: 'transparent', fontWeight: 700 }}>Archived</button>
          </div>
          <div style={{ display: 'flex', gap: 8 }}>
             <Search size={18} color="var(--text-muted)" style={{ cursor: 'pointer' }} />
             <Filter size={18} color="var(--text-muted)" style={{ cursor: 'pointer' }} />
          </div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column' }}>
          {notifications.map(n => (
            <div key={n.id} style={{
              display: 'flex', gap: 16, padding: '20px 24px', borderBottom: '1px solid var(--border)',
              background: n.read ? 'transparent' : 'rgba(124, 58, 237, 0.03)',
              transition: '0.2s', position: 'relative'
            }}>
              {!n.read && <div style={{ position: 'absolute', left: 0, top: 0, bottom: 0, width: 4, background: accentColor }} />}
              
              <div style={{ 
                width: 44, height: 44, borderRadius: 12, 
                background: 'white', border: '1px solid var(--border)',
                display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
                boxShadow: '0 2px 8px rgba(0,0,0,0.04)'
              }}>
                {getIcon(n.type)}
              </div>

              <div style={{ flex: 1 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 4 }}>
                  <h4 style={{ margin: 0, fontSize: '0.9375rem', fontWeight: 800 }}>{n.title}</h4>
                  <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', fontWeight: 600 }}>{n.time}</span>
                </div>
                <p style={{ margin: 0, fontSize: '0.875rem', color: 'var(--text-secondary)', lineHeight: 1.5 }}>{n.message}</p>
              </div>

              <button 
                className="btn-icon" 
                onClick={() => deleteOne(n.id)}
                style={{ alignSelf: 'center', color: 'var(--text-muted)' }}
              >
                <Trash2 size={16} />
              </button>
            </div>
          ))}

          {notifications.length === 0 && (
            <div style={{ padding: '80px 24px', textAlign: 'center' }}>
              <Bell size={48} color="var(--text-muted)" style={{ margin: '0 auto 16px', opacity: 0.3 }} />
              <h3 style={{ fontWeight: 800, color: 'var(--text-secondary)' }}>All caught up!</h3>
              <p style={{ color: 'var(--text-muted)' }}>No new notifications to show right now.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
